version: '2.2'
services:
  lambdatrader:
    extends:
      file: docker-compose.base.yml
      service: lambdatrader

  lambdatrader1:
    extends:
      file: docker-compose.base.yml
      service: lambdatrader
    env_file:
      - exclude/configs/lambdatrader1.env

  lambdatrader2:
    extends:
      file: docker-compose.base.yml
      service: lambdatrader
    env_file:
      - exclude/configs/lambdatrader2.env

volumes:
  mongodata:
