version: '2.2'
services:
  lambdatrader:
    extends:
      file: docker-compose.base.yml
      service: lambdatrader
    depends_on:
      - mongodb

  lambdatrader1:
    extends:
      file: docker-compose.base.yml
      service: lambdatrader
    depends_on:
      - mongodb
    env_file:
      - exclude/configs/lambdatrader1.env

  lambdatrader2:
    extends:
      file: docker-compose.base.yml
      service: lambdatrader
    depends_on:
      - mongodb
    env_file:
      - exclude/configs/lambdatrader2.env

  mongodb:
    image: "mongo:3.4"
    volumes:
      - "mongodata:/data/db"


volumes:
  mongodata:
