version: '3'
services:
  lambdatrader:
    build: .
    command: python3 -m lambdatrader.livetrade
    volumes:
      - "${HISTORY_DB_HOST_PATH}:${HISTORY_DB_DOCKER_PATH}"
    env_file:
      - .env
    depends_on:
      - mongodb
      - candlestick-fetcher

  candlestick-fetcher:
    build: .
    command: python3 -m lambdatrader.sync_polx_candlesticks
    volumes:
      - "${HISTORY_DB_HOST_PATH}:${HISTORY_DB_DOCKER_PATH}"
    env_file:
      - .env

  mongodb:
    image: "mongo:3.4"
    volumes:
      - "mongodata:/data/db"

volumes:
  mongodata:
